with Ada.Characters.Handling;

with Tada.Package_Cache;

package body Tada.Templates is
   procedure Emit
     (Path : String;
      Write : access procedure (File : File_Type;
                                Name : String);
      Name : String)
   is
      File : File_Type;
   begin
      Create (File, Out_File, Path);
      Write (File, Name);
      Close (File);
   end Emit;

   procedure Emit
     (Path : String;
      Write : access procedure (File : File_Type;
                                Name : String;
                                Kind : Package_Kind);
      Name : String;
      Kind : Package_Kind)
   is
      File : File_Type;
   begin
      Create (File, Out_File, Path);
      Write (File, Name, Kind);
      Close (File);
   end Emit;

   procedure Emit
     (Path : String;
      Write : access procedure (File : File_Type;
                                Name : String;
                                Deps : Package_Info_Vectors.Vector);
      Name : String;
      Deps : Package_Info_Vectors.Vector)
   is
      File : File_Type;
   begin
      Create (File, Out_File, Path);
      Write (File, Name, Deps);
      Close (File);
   end Emit;

   function Mixed_Case (Name : String) return String is
      Result : String := Name;
      Cap_Next : Boolean := True;
   begin
      for I in Result'Range loop
         if Result (I) = '_' then
            Cap_Next := True;
         elsif Cap_Next then
            Result (I) := Characters.Handling.To_Upper (Result (I));
            Cap_Next := False;
         end if;
      end loop;

      return Result;
   end Mixed_Case;

   procedure Write_Readme (File : File_Type; Name : String) is
   begin
      Put_Line (File, "# " & Mixed_Case (Name));
   end Write_Readme;

   procedure Write_Manifest (File : File_Type; Name : String) is
   begin
      Put_Line (File, "[package]");
      Put_Line (File, "name = """ & Name & """");
      Put_Line (File, "version = ""0.1.0-dev""");
      New_Line (File);
      Put_Line (File, "[dependencies]");
      New_Line (File);
      Put_Line (File, "[dev-dependencies]");
      Put_Line (File, "testy = ""0.1.0""");
   end Write_Manifest;

   procedure Write_Gitignore (File : File_Type; Name : String) is
   begin
      Put_Line (File, ".tada/");
      Put_Line (File, "target/");
      Put_Line (File, Name & "_deps.gpr");
      Put_Line (File, Name & "_tests_deps.gpr");
   end Write_Gitignore;

   procedure Write_GPR_Config (File : File_Type; Name : String) is
      MC : constant String := Mixed_Case (Name);
   begin
      Put_Line (File, "abstract project " & MC & "_Config is");
      Put_Line (File, "   type Build_Profile_Kind is (""debug"", ""release"");");
      Put_Line (File, "   Build_Profile : Build_Profile_Kind :=");
      Put_Line (File, "     external (""BUILD_PROFILE"", ""debug"");");
      Put_Line (File, "");
      Put_Line (File, "   Common_Switches := (""-gnat2022"", ""-gnatwa"", ""-gnata"");");
      Put_Line (File, "   Style_Switches := (""-gnatyaAbCdefhiklnOprStux"");");
      Put_Line (File, "");
      Put_Line (File, "   Debug_Switches := Common_Switches &");
      Put_Line (File, "     (""-g"",       --  Debug info");
      Put_Line (File, "      ""-O0"",      --  No optimization");
      Put_Line (File, "      ""-gnateE"",  --  Extra exception info");
      Put_Line (File, "      ""-gnatVa""); --  All validity checks");
      Put_Line (File, "");
      Put_Line (File, "   Release_Switches := Common_Switches &");
      Put_Line (File, "     (""-O2"",          --  Optimization");
      Put_Line (File, "      ""-gnatn"",       --  Inlining");
      Put_Line (File, "      ""-fdata-sections"",");
      Put_Line (File, "      ""-ffunction-sections"");");
      Put_Line (File, "");
      Put_Line (File, "   Ada_Switches := ();");
      Put_Line (File, "   case Build_Profile is");
      Put_Line (File, "      when ""debug""   => Ada_Switches := Debug_Switches;");
      Put_Line (File, "      when ""release"" => Ada_Switches := Release_Switches;");
      Put_Line (File, "   end case;");
      Put_Line (File, "");
      Put_Line (File, "   Linker_Switches := ();");
      Put_Line (File, "   case Build_Profile is");
      Put_Line (File, "      when ""debug""   => Linker_Switches := ();");
      Put_Line (File, "      when ""release"" => Linker_Switches := ();");
      Put_Line (File, "   end case;");
      Put_Line (File, "end " & MC & "_Config;");
   end Write_GPR_Config;

   procedure Write_GPR_Deps (File : File_Type; Name : String; Deps : Package_Info_Vectors.Vector := Package_Info_Vectors.Empty_Vector) is
      MC : constant String := Mixed_Case (Name);
   begin
      Put_Line (File, "--  generated by tada, do not edit");
      for C in Deps.Iterate loop
         Put_Line (File, "with """ & Package_Cache.GPR_Path (Package_Info_Vectors.Element (C)) & """;");
      end loop;
      Put_Line (File, "abstract project " & MC & "_Deps is");
      Put_Line (File, "end " & MC & "_Deps;");
   end Write_GPR_Deps;

   procedure Write_GPR_Main (File : File_Type; Name : String; Kind : Package_Kind) is
      MC : constant String := Mixed_Case (Name);
   begin
      Put_Line (File, "with """ & Name & "_config.gpr"";");
      Put_Line (File, "with """ & Name & "_deps.gpr"";");
      Put_Line (File, "");
      Put_Line (File, "project " & MC & " is");
      Put_Line (File, "   for Source_Dirs use (""src"");");
      Put_Line (File, "   for Object_Dir use ""target/"" & " & MC & "_Config.Build_Profile & ""/obj"";");

      case Kind is
         when Exe =>
            Put_Line (File, "   for Exec_Dir use ""target/"" & " & MC & "_Config.Build_Profile & ""/bin"";");
            Put_Line (File, "   for Main use (""" & Name & "-main.adb"");");
            Put_Line (File, "");
            Put_Line (File, "   package Builder is");
            Put_Line (File, "      for Executable (""" & Name & "-main.adb"") use """ & Name & """;");
            Put_Line (File, "   end Builder;");
            Put_Line (File, "");
            Put_Line (File, "   package Compiler is");
            Put_Line (File, "      for Default_Switches (""Ada"") use");
            Put_Line (File, "        " & MC & "_Config.Ada_Switches &");
            Put_Line (File, "        " & MC & "_Config.Style_Switches;");
            Put_Line (File, "   end Compiler;");
            Put_Line (File, "");
            Put_Line (File, "   package Binder is");
            Put_Line (File, "      for Default_Switches (""Ada"") use (""-Es"");");
            Put_Line (File, "   end Binder;");
            Put_Line (File, "");
            Put_Line (File, "   package Linker is");
            Put_Line (File, "      for Default_Switches (""Ada"") use");
            Put_Line (File, "        " & MC & "_Config.Linker_Switches;");
            Put_Line (File, "   end Linker;");

         when Lib =>
            Put_Line (File, "   for Library_Name use """ & Name & """;");
            Put_Line (File, "   for Library_Dir use ""target/"" & " & MC & "_Config.Build_Profile & ""/lib"";");
            Put_Line (File, "   for Library_Kind use ""static"";");
            Put_Line (File, "");
            Put_Line (File, "   package Compiler is");
            Put_Line (File, "      for Default_Switches (""Ada"") use");
            Put_Line (File, "        " & MC & "_Config.Ada_Switches &");
            Put_Line (File, "        " & MC & "_Config.Style_Switches;");
            Put_Line (File, "   end Compiler;");
      end case;

      Put_Line (File, "end " & MC & ";");
   end Write_GPR_Main;

   procedure Write_GPR_Tests (File : File_Type; Name : String) is
      MC : constant String := Mixed_Case (Name);
   begin
      Put_Line (File, "with """ & Name & "_config.gpr"";");
      Put_Line (File, "with """ & Name & "_tests_deps.gpr"";");
      Put_Line (File, "with """ & Name & ".gpr"";");
      Put_Line (File, "");
      Put_Line (File, "project " & MC & "_Tests is");
      Put_Line (File, "   for Source_Dirs use (""tests"");");
      Put_Line (File, "   for Object_Dir use ""target/"" & " & MC & "_Config.Build_Profile & ""/obj-tests"";");
      Put_Line (File, "   for Exec_Dir use ""target/"" & " & MC & "_Config.Build_Profile & ""/bin"";");
      Put_Line (File, "   for Main use (""tests_main.adb"");");
      Put_Line (File, "");
      Put_Line (File, "   package Builder is");
      Put_Line (File, "      for Executable (""tests_main.adb"") use ""tests"";");
      Put_Line (File, "   end Builder;");
      Put_Line (File, "");
      Put_Line (File, "   package Compiler is");
      Put_Line (File, "      for Default_Switches (""Ada"") use");
      Put_Line (File, "        " & MC & "_Config.Ada_Switches &");
      Put_Line (File, "        " & MC & "_Config.Style_Switches;");
      Put_Line (File, "   end Compiler;");
      Put_Line (File, "");
      Put_Line (File, "   package Binder is");
      Put_Line (File, "      for Default_Switches " & "(""Ada"") use (""-Es"");");
      Put_Line (File, "   end Binder;");
      Put_Line (File, "end " & MC & "_Tests;");
   end Write_GPR_Tests;

   procedure Write_Tests_Runner (File : File_Type; Name : String) is
      MC : constant String := Mixed_Case (Name);
   begin
      Put_Line (File, "with Testy.Runners;");
      Put_Line (File, "with Testy.Reporters.Text;");
      Put_Line (File, "");
      Put_Line (File, "with " & MC & "_Tests;");
      Put_Line (File, "");
      Put_Line (File, "procedure Tests_Main is");
      Put_Line (File, "   use Testy;");
      Put_Line (File, "");
      Put_Line (File, "   Test_Runner : Runners.Runner := Runners.Create;");
      Put_Line (File, "   Test_Reporter : Reporters.Text.Text_Reporter;");
      Put_Line (File, "begin");
      Put_Line (File, "   Test_Runner.Add (""True is True"", " & MC & "_Tests.True_Is_True'Access);");
      Put_Line (File, "");
      Put_Line (File, "   Test_Runner.Run (Test_Reporter);");
      Put_Line (File, "end Tests_Main;");
   end Write_Tests_Runner;

   procedure Write_Tests_Spec (File : File_Type; Name : String) is
      MC : constant String := Mixed_Case (Name);
   begin
      Put_Line (File, "with Testy.Tests;");
      Put_Line (File, "");
      Put_Line (File, "package " & MC & "_Tests is");
      Put_Line (File, "   use Testy.Tests;");
      Put_Line (File, "");
      Put_Line (File, "   procedure True_Is_True (T : in out Test_Context);");
      Put_Line (File, "end " & MC & "_Tests;");
   end Write_Tests_Spec;

   procedure Write_Tests_Body (File : File_Type; Name : String) is
      MC : constant String := Mixed_Case (Name);
   begin
      Put_Line (File, "package body " & MC & "_Tests is");
      Put_Line (File, "   procedure True_Is_True (T : in out Test_Context) is");
      Put_Line (File, "   begin");
      Put_Line (File, "      T.Expect (True, ""expected True"");");
      Put_Line (File, "   end True_Is_True;");
      Put_Line (File, "end " & MC & "_Tests;");
   end Write_Tests_Body;

   procedure Write_Root_Package_Spec (File : File_Type; Name : String; Kind : Package_Kind) is
      MC : constant String := Mixed_Case (Name);
   begin
      case Kind is
         when Exe =>
            Put_Line (File, "package " & MC & " is");
            Put_Line (File, "   pragma Pure;");
            Put_Line (File, "end " & MC & ";");

         when Lib =>
            Put_Line (File, "package " & MC & " is");
            Put_Line (File, "   procedure Hello;");
            Put_Line (File, "end " & MC & ";");
      end case;
   end Write_Root_Package_Spec;

   procedure Write_Main_Spec (File : File_Type; Name : String) is
      MC : constant String := Mixed_Case (Name);
   begin
      Put_Line (File, "procedure " & MC & ".Main;");
   end Write_Main_Spec;

   procedure Write_Main_Body (File : File_Type; Name : String) is
      MC : constant String := Mixed_Case (Name);
   begin
      Put_Line (File, "with Ada.Text_IO;");
      Put_Line (File, "");
      Put_Line (File, "procedure " & MC & ".Main is");
      Put_Line (File, "begin");
      Put_Line (File, "   Ada.Text_IO.Put_Line (""Hello from " & MC & "!"");");
      Put_Line (File, "end " & MC & ".Main;");
   end Write_Main_Body;

   procedure Write_Root_Package_Body (File : File_Type; Name : String) is
      MC : constant String := Mixed_Case (Name);
   begin
      Put_Line (File, "with Ada.Text_IO;");
      Put_Line (File, "");
      Put_Line (File, "package body " & MC & " is");
      Put_Line (File, "   procedure Hello is");
      Put_Line (File, "   begin");
      Put_Line (File, "      Ada.Text_IO.Put_Line (""Hello from " & MC & "!"");");
      Put_Line (File, "   end Hello;");
      Put_Line (File, "end " & MC & ";");
   end Write_Root_Package_Body;
end Tada.Templates;
